const mermaAcciones = {
    // Form actions
    CHANGE_VALUE: "CHANGE_VALUE",
    CHANGE_VALUE_FORM: "CHANGE_VALUE_FORM",
    CHANGE_VALUE_FILTER: "CHANGE_VALUE_FILTER",
    SET_FORM_DATA: "SET_FORM_DATA",

    // Data loading
    LOAD_MERMAS: "LOAD_MERMAS",
    LOAD_MERMAS_SUCCESS: "LOAD_MERMAS_SUCCESS",
    LOAD_MERMAS_ERROR: "LOAD_MERMAS_ERROR",

    // Selection & UI
    TOGGLE_SELECT_MERMA: "TOGGLE_SELECT_MERMA",
    TOGGLE_AGREGAR_MODAL: "TOGGLE_AGREGAR_MODAL",
    TOGGLE_FILTERS_MODAL: "TOGGLE_FILTERS_MODAL",

    // Pagination & sorting
    CHANGE_PAGE: "CHANGE_PAGE",
    CHANGE_ITEMS_PER_PAGE: "CHANGE_ITEMS_PER_PAGE",
    SORT_MERMAS: "SORT_MERMAS",

    // Filters
    APPLY_FILTERS: "APPLY_FILTERS",
    RESET_FILTERS: "RESET_FILTERS",

    // Form operations
    SUBMIT_MERMA: "SUBMIT_MERMA",
    RESET_FORM: "RESET_FORM"
};

export default mermaAcciones;